# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

encoding: UTF-8

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: debiantarte
title: debiantarte.github.io
email: pierre.bidault@telecom-sudparis.eu
author: Pierre "debiantarte" Bidault
copyright: 2020
description: >- # this means to ignore newlines until "baseurl:"
    My portfolio site to showcase all the projects I have been working on.
baseurl: "" # the subpath of your site, e.g. /blog

# PROD_URL
url: "https://debiantarte.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# DEBUG_URL
#url: "http://localhost:4000"


github_username: debiantarte

# Build settings
markdown: kramdown
lang: en

# Theme settings (thanks to https://github.com/streetturtle/jekyll-clean-dark)
comments: false
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

# Collections
collections:
  projects:
    output: true
  tags:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
